# Message when you get tagged
tag_message: "&cYou got tagged!"
# Message when you tag a player
tagger_message: "&aYou tagged {tagged}!"
# Message in the console with who tagged who
console_message: "&7{tagger} tagged {tagged}!"
# Global server message for other players
global_message: "&6{tagger} tagged {tagged}!"
# Cooldown on the tag, default is 5 seconds
tag_cooldown: 5
# Message when the game starts
game_start_message: "&aThe tag game has started!"

game-settings:
  speed: 1       # Speed of the players(between 1 and 5)
  borderSize: 5 # Size of the border (in chunks)
  duration: 2   # Duration of the game (in minutes)

# Saved Playsigns
signs: []