name: Tagplugin
main: me.galaxy1007.tagplugin.Tagplugin
version: 1.0
api-version: 1.21
commands:
  taggame:
    description: Main command for the taggame
    usage: /taggame <subcommand>
    aliases:
      - tg
      - TG
    tab-completer: me.galaxy1007.tagplugin.TagGameTabCompleter